microserviceConfig:
   microservice-FMIS:
    JZFMISESPSVR:
      context: EnterpriseServer
      objectName:
        SecurityObject:
          method: initApplication
   microservice-KJDA:        
    KJDAServer:
      context: EnterpriseServer
      objectName:
        SecurityObject:
          method: getUserFunctionLimit
  





