spring:
  zipkin:
    base-url: http://localhost:8099
  sleuth:
    sampler:
      percentage: 1.0
  application:
    name: user-service
logging:
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: debug